//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilkySouls2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilkySouls2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 60             sub    rsp,0x60
        ///48 8d 0d 00 00 00 00    lea    rcx,[rip+0x0]        # b &lt;_main+0xb&gt;
        ///0f b7 15 00 00 00 00    movzx  edx,WORD PTR [rip+0x0]        # 12 &lt;_main+0x12&gt;
        ///41 b8 05 00 00 00       mov    r8d,0x5
        ///e8 00 00 00 00          call   1d &lt;_main+0x1d&gt;
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 8d 15 00 00 00 00    lea    rdx,[rip+0x0]        # 2e &lt;_main+0x2e&gt;
        ///e8 00 00 00 00          call   33 &lt;_main+0x33&gt;
        ///48 83 c4 60             add    rsp,0x60
        ///c3                       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BonfireWarp {
            get {
                return ResourceManager.GetString("BonfireWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44 8b 41 1c             mov    r8d,DWORD PTR [rcx+0x1c]
        ///53                      push   rbx
        ///8b 1d 00 00 00 00       mov    ebx,DWORD PTR [rip+0x0]        # b &lt;_main+0xb&gt;
        ///3b 5a 68                cmp    ebx,DWORD PTR [rdx+0x68]
        ///75 0b                   jne    1b &lt;original&gt;
        ///ba 64 00 00 00          mov    edx,0x64
        ///5b                      pop    rbx
        ///e9 00 00 00 00          jmp    1b &lt;original&gt;
        ///00000000001b &lt;original&gt;:
        ///8b 54 82 40             mov    edx,DWORD PTR [rdx+rax*4+0x40]
        ///5b                      p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompareEventRandValue {
            get {
                return ResourceManager.GetString("CompareEventRandValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51                      push   rcx
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 8b 09                mov    rcx,QWORD PTR [rcx]
        ///48 8b 89 d0 00 00 00    mov    rcx,QWORD PTR [rcx+0xd0]
        ///48 39 d9                cmp    rcx,rbx
        ///74 02                   je     1c &lt;is_player&gt;
        ///eb 11                   jmp    2d &lt;check_target&gt;
        ///00000000001c &lt;is_player&gt;:
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # 23 &lt;is_player+0x7&gt;
        ///74 46                   je     6b &lt;exit&gt;
        ///8b 81 68 01 00 00       mov  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DamageControl {
            get {
                return ResourceManager.GetString("DamageControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8b 05 00 00 00 00       mov    eax,DWORD PTR [rip+0x0]        # 6 &lt;_main+0x6&gt;
        ///e9 00 00 00 00          jmp    b &lt;_main+0xb&gt;.
        /// </summary>
        internal static string OverrideGeneratorStartPositionRandom {
            get {
                return ResourceManager.GetString("OverrideGeneratorStartPositionRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 3d 00 00 00 00    mov    QWORD PTR [rip+0x0],rdi        # 7 &lt;_main+0x7&gt;
        ///48 89 bb c0 00 00 00    mov    QWORD PTR [rbx+0xc0],rdi
        ///e9 00 00 00 00          jmp    13 &lt;_main+0x13&gt;.
        /// </summary>
        internal static string SaveTargetPtr {
            get {
                return ResourceManager.GetString("SaveTargetPtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49 8b 8f b0 00 00 00    mov    rcx,QWORD PTR [r15+0xb0]
        ///53                      push   rbx
        ///8b 1d 00 00 00 00       mov    ebx,DWORD PTR [rip+0x0]        # e &lt;_main+0xe&gt;
        ///41 3b 5f 68             cmp    ebx,DWORD PTR [r15+0x68]
        ///75 06                   jne    1a &lt;skip&gt;
        ///8b 35 00 00 00 00       mov    esi,DWORD PTR [rip+0x0]        # 1a &lt;skip&gt;
        ///00000000001a &lt;skip&gt;:
        ///5b                      pop    rbx
        ///e9 00 00 00 00          jmp    20 &lt;skip+0x6&gt;.
        /// </summary>
        internal static string SetAreaVariable {
            get {
                return ResourceManager.GetString("SetAreaVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///41 b8 00 00 00 00       mov    r8d,0x0
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret
        ///.
        /// </summary>
        internal static string SetEventOff {
            get {
                return ResourceManager.GetString("SetEventOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///41 b8 01 00 00 00       mov    r8d,0x1
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string SetEventOn {
            get {
                return ResourceManager.GetString("SetEventOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0f 5c c2                subps  xmm0,xmm2
        ///0f 29 47 50             movaps XMMWORD PTR [rdi+0x50],xmm0
        ///50                      push   rax
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 8b 00                mov    rax,QWORD PTR [rax]
        ///48 8b 40 58             mov    rax,QWORD PTR [rax+0x58]
        ///48 8b 80 f8 01 00 00    mov    rax,QWORD PTR [rax+0x1f8]
        ///48 8b 40 18             mov    rax,QWORD PTR [rax+0x18]
        ///48 8b 40 08             mov    rax,QWORD PTR [rax+0x8]
        ///48 05 50 01 00 00       add    rax,0x150
        ///48 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WarpCoordWrite {
            get {
                return ResourceManager.GetString("WarpCoordWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10655,Boss,Last Giant,92.18|-40.43|-147.47|0.00|92.18|-40.43|-147.47|55.84|92.18|-40.43|-147.47|0.00|0.00|0.00|0.00|1.00
        ///10655,Boss,Pursuer,139.12|10.05|-217.90|0.00|139.12|10.05|-217.90|58.79|139.12|10.05|-217.90|0.00|0.00|0.00|0.00|1.00
        ///31650,Boss,Dragonrider,-6.91|-14.66|283.71|0.00|-6.91|-14.66|283.71|36.76|-6.91|-14.66|283.71|0.00|0.00|0.00|0.00|1.00
        ///31660,Boss,Ornstein,-144.09|8.03|170.72|0.00|-144.09|8.03|170.72|45.42|-144.09|8.03|170.72|0.00|0.00|0.00|0.00|1.00
        ///18650,Boss,Flexile,2.91|-65.35|514 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WarpLocations {
            get {
                return ResourceManager.GetString("WarpLocations", resourceCulture);
            }
        }
    }
}
