//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilkySouls2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilkySouls2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44 8b 41 1c             mov    r8d,DWORD PTR [rcx+0x1c]
        ///53                      push   rbx
        ///48 8b 1d 00 00 00 00    mov    rbx,QWORD PTR [rip+0x0]        # c &lt;_main+0xc&gt;
        ///48 3b 5a 68             cmp    rbx,QWORD PTR [rdx+0x68]
        ///75 0b                   jne    1d &lt;original&gt;
        ///ba 64 00 00 00          mov    edx,0x64
        ///5b                      pop    rbx
        ///e9 00 00 00 00          jmp    1d &lt;original&gt;
        ///00000000001d &lt;original&gt;:
        ///8b 54 82 40             mov    edx,DWORD PTR [rdx+rax*4+0x40]
        ///5b                      p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompareEventRandValue {
            get {
                return ResourceManager.GetString("CompareEventRandValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8b 05 00 00 00 00       mov    eax,DWORD PTR [rip+0x0]        # 6 &lt;_main+0x6&gt;
        ///e9 00 00 00 00          jmp    b &lt;_main+0xb&gt;.
        /// </summary>
        internal static string OverrideGeneratorStartPositionRandom {
            get {
                return ResourceManager.GetString("OverrideGeneratorStartPositionRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 88 74 24 28          mov    BYTE PTR [rsp+0x28],sil
        ///53                      push   rbx
        ///48 8b 1d 00 00 00 00    mov    rbx,QWORD PTR [rip+0x0]        # d &lt;_main+0xd&gt;
        ///48 3b 5e 68             cmp    rbx,QWORD PTR [rsi+0x68]
        ///75 0c                   jne    1f &lt;original&gt;
        ///8b 2d 00 00 00 00       mov    ebp,DWORD PTR [rip+0x0]        # 19 &lt;_main+0x19&gt;
        ///5b                      pop    rbx
        ///e9 00 00 00 00          jmp    1f &lt;original&gt;
        ///00000000001f &lt;original&gt;:
        ///89 6c 24 2c             mov    DWORD PTR [rsp+0x2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SetAreaVariable {
            get {
                return ResourceManager.GetString("SetAreaVariable", resourceCulture);
            }
        }
    }
}
