//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilkySouls2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilkySouls2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60760000,Wood Arrow,999,0,0
        ///60770000,Iron Arrow,999,0,0
        ///60780000,Magic Arrow,999,0,0
        ///60790000,Lightning Arrow,999,0,0
        ///60800000,Fire Arrow,999,0,0
        ///60810000,Dark Arrow,999,0,0
        ///60820000,Poison Arrow,999,0,0
        ///60830000,Lacerating Arrow,999,0,0
        ///60850000,Iron Greatarrow,999,0,0
        ///60870000,Lightning Greatarrow,999,0,0
        ///60880000,Fire Greatarrow,999,0,0
        ///60900000,Destructive Greatarrow,999,0,0
        ///60910000,Wood Bolt,999,0,0
        ///60920000,Heavy Bolt,999,0,0
        ///60930000,Magic Bolt,999,0,0
        ///60940000,Lightning Bolt,999,0,0        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ammo {
            get {
                return ResourceManager.GetString("Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25060101,Agdayne&apos;s Black Robe,1,5,0
        ///25060102,Agdayne&apos;s Cuffs,1,5,0
        ///25060103,Agdayne&apos;s Kilt,1,5,0
        ///23060101,Alonne Captain Armor,1,10,0
        ///23060100,Alonne Captain Helm,1,10,0
        ///23061101,Alonne Knight Armor,1,10,0
        ///23061102,Alonne Knight Gauntlets,1,10,0
        ///23061100,Alonne Knight Helm,1,10,0
        ///23061103,Alonne Knight Leggings,1,10,0
        ///26800101,Alonne&apos;s Armor,1,5,0
        ///26800102,Alonne&apos;s Gauntlets,1,5,0
        ///26800100,Alonne&apos;s Helm,1,5,0
        ///26800103,Alonne&apos;s Leggings,1,5,0
        ///21490101,Alva Armor,1,10,0
        ///21490102,Alva Gauntlets,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 60             sub    rsp,0x60
        ///48 8d 0d 00 00 00 00    lea    rcx,[rip+0x0]        # b &lt;_main+0xb&gt;
        ///0f b7 15 00 00 00 00    movzx  edx,WORD PTR [rip+0x0]        # 12 &lt;_main+0x12&gt;
        ///41 b8 05 00 00 00       mov    r8d,0x5
        ///e8 00 00 00 00          call   1d &lt;_main+0x1d&gt;
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 8d 15 00 00 00 00    lea    rdx,[rip+0x0]        # 2e &lt;_main+0x2e&gt;
        ///e8 00 00 00 00          call   33 &lt;_main+0x33&gt;
        ///48 83 c4 60             add    rsp,0x60
        ///c3                       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BonfireWarp {
            get {
                return ResourceManager.GetString("BonfireWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44 8b 41 1c             mov    r8d,DWORD PTR [rcx+0x1c]
        ///53                      push   rbx
        ///8b 1d 00 00 00 00       mov    ebx,DWORD PTR [rip+0x0]        # b &lt;_main+0xb&gt;
        ///3b 5a 68                cmp    ebx,DWORD PTR [rdx+0x68]
        ///75 0b                   jne    1b &lt;original&gt;
        ///ba 64 00 00 00          mov    edx,0x64
        ///5b                      pop    rbx
        ///e9 00 00 00 00          jmp    1b &lt;original&gt;
        ///00000000001b &lt;original&gt;:
        ///8b 54 82 40             mov    edx,DWORD PTR [rdx+rax*4+0x40]
        ///5b                      p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompareEventRandValue {
            get {
                return ResourceManager.GetString("CompareEventRandValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60010000,Lifegem,99,0,0
        ///60020000,Radiant Lifegem,99,0,0
        ///60030000,Old Radiant Lifegem,99,0,0
        ///60035000,Elizabeth Mushroom,99,0,0
        ///60036000,Dried Root,99,0,0
        ///60040000,Amber Herb,99,0,0
        ///60050000,Twilight Herb,99,0,0
        ///60060000,Wilted Dusk Herb,99,0,0
        ///60070000,Poison Moss,99,0,0
        ///60090000,Monastery Charm,99,0,0
        ///60100000,Dragon Charm,99,0,0
        ///60105000,Divine Blessing,99,0,0
        ///60110000,Rouge Water,99,0,0
        ///60120000,Crimson Water,99,0,0
        ///60151000,Human Effigy,99,0,0
        ///60160000,Small Blue Burr,99,0,0
        ///60170000,Sma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Consumables {
            get {
                return ResourceManager.GetString("Consumables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 81 ec 20 02 00 00    sub    rsp,0x220
        ///83 3d 00 00 00 00 00    cmp    DWORD PTR [rip+0x0],0x0        # e &lt;_main+0xe&gt;
        ///75 11                   jne    21 &lt;skip&gt;
        ///c7 41 28 07 00 00 00    mov    DWORD PTR [rcx+0x28],0x7
        ///c7 05 00 00 00 00 01    mov    DWORD PTR [rip+0x0],0x1        # 21 &lt;skip&gt;
        ///00 00 00
        ///000000000021 &lt;skip&gt;:
        ///e9 00 00 00 00          jmp    26 &lt;skip+0x5&gt;.
        /// </summary>
        internal static string CreditSkip {
            get {
                return ResourceManager.GetString("CreditSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0f 29 74 24 20          movaps XMMWORD PTR [rsp+0x20],xmm6
        ///41 83 78 34 00          cmp    DWORD PTR [r8+0x34],0x0
        ///74 6a                   je     76 &lt;skip&gt;
        ///51                      push   rcx
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 8b 09                mov    rcx,QWORD PTR [rcx]
        ///48 8b 89 d0 00 00 00    mov    rcx,QWORD PTR [rcx+0xd0]
        ///48 39 c1                cmp    rcx,rax
        ///74 4f                   je     75 &lt;exit&gt;
        ///49 3b 41 68             cmp    rax,QWORD PTR [r9+0x68]
        ///74 06                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DamageControl {
            get {
                return ResourceManager.GetString("DamageControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 47 08             mov    rax,QWORD PTR [rdi+0x8]
        ///81 78 28 e0 2e 00 00    cmp    DWORD PTR [rax+0x28],0x2ee0
        ///75 0f                   jne    1d &lt;check_alonne&gt;
        ///48 31 c0                xor    rax,rax
        ///48 85 c0                test   rax,rax
        ///58                      pop    rax
        ///89 73 18                mov    DWORD PTR [rbx+0x18],esi
        ///e9 00 00 00 00          jmp    1d &lt;check_alonne&gt;
        ///00000000001d &lt;check_alonne&gt;:
        ///81 78 28 d8 d6 00 00    cmp    DWORD PTR [rax+0x28],0xd6d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DisableMemoryTimer {
            get {
                return ResourceManager.GetString("DisableMemoryTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 81 fa 5e 1f 02 20    cmp    rdx,0x20021f5e
        ///75 03                   jne    c &lt;normal&gt;
        ///4d 31 c0                xor    r8,r8
        ///00000000000c &lt;normal&gt;:
        ///41 0f b6 f8             movzx  edi,r8b
        ///48 8b 88 f0 22 00 00    mov    rcx,QWORD PTR [rax+0x22f0]
        ///e9 00 00 00 00          jmp    1c &lt;normal+0x10&gt;.
        /// </summary>
        internal static string DisableSnowstorm {
            get {
                return ResourceManager.GetString("DisableSnowstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 fa                mov    rdx,rdi
        ///48 89 d9                mov    rcx,rbx
        ///83 3d 00 00 00 00 00    cmp    DWORD PTR [rip+0x0],0x0        # d &lt;_main+0xd&gt;
        ///0f 84 00 00 00 00       je     13 &lt;_main+0x13&gt;
        ///50                      push   rax
        ///57                      push   rdi
        ///8b 3d 00 00 00 00       mov    edi,DWORD PTR [rip+0x0]        # 1b &lt;_main+0x1b&gt;
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///000000000025 &lt;loop_start&gt;:
        ///83 ff 00                cmp    edi,0x0
        ///7e 0d                   jle    37  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DisableTargetAi {
            get {
                return ResourceManager.GetString("DisableTargetAi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b8 0a 00 00 00          mov    eax,0xa
        ///e9 00 00 00 00          jmp    a &lt;_main+0xa&gt;.
        /// </summary>
        internal static string DropCount {
            get {
                return ResourceManager.GetString("DropCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 81 ec 18 01 00 00    sub    rsp,0x118
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 8d 15 00 00 00 00    lea    rdx,[rip+0x0]        # 18 &lt;_main+0x18&gt;
        ///e8 00 00 00 00          call   1d &lt;_main+0x1d&gt;
        ///48 81 c4 18 01 00 00    add    rsp,0x118
        ///c3                      ret.
        /// </summary>
        internal static string EventWarp {
            get {
                return ResourceManager.GetString("EventWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 84 24 50 01 00    mov    QWORD PTR [rsp+0x150],rax
        ///00
        ///83 7f 08 17             cmp    DWORD PTR [rdi+0x8],0x17
        ///75 07                   jne    15 &lt;exit&gt;
        ///c7 47 08 47 00 00 00    mov    DWORD PTR [rdi+0x8],0x47
        ///000000000015 &lt;exit&gt;:
        ///e9 00 00 00 00          jmp    1a &lt;exit+0x5&gt;.
        /// </summary>
        internal static string FastQuitout {
            get {
                return ResourceManager.GetString("FastQuitout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 63000000,Point Gesture,1,0,0
        ///63001000,I won&apos;t bite Gesture,1,0,0
        ///63003000,Bow Gesture,1,0,0
        ///63004000,Welcome Gesture,1,0,0
        ///63005000,Duel bow Gesture,1,0,0
        ///63006000,Wave Gesture,1,0,0
        ///63007000,Pumped up Gesture,1,0,0
        ///63008000,Joy Gesture,1,0,0
        ///63009000,Warcry Gesture,1,0,0
        ///63010000,Warmup Gesture,1,0,0
        ///63011000,Hurrah! Gesture,1,0,0
        ///63012000,Righty-ho! Gesture,1,0,0
        ///63013000,No way Gesture,1,0,0
        ///63014000,This one&apos;s me Gesture,1,0,0
        ///63015000,Have mercy! Gesture,1,0,0
        ///63016000,Prostration Gestur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Gestures {
            get {
                return ResourceManager.GetString("Gestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 83 ec 48             sub    rsp,0x48
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 48             add    rsp,0x48
        ///c3                      ret.
        /// </summary>
        internal static string GiveSouls {
            get {
                return ResourceManager.GetString("GiveSouls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 8b 00                mov    rax,QWORD PTR [rax]
        ///48 39 88 d0 00 00 00    cmp    QWORD PTR [rax+0xd0],rcx
        ///75 09                   jne    20 &lt;normal&gt;
        ///83 bd ec 05 00 00 ff    cmp    DWORD PTR [rbp+0x5ec],0xffffffff
        ///eb 06                   jmp    26 &lt;exit&gt;
        ///000000000020 &lt;normal&gt;:
        ///39 9d ec 05 00 00       cmp    DWORD PTR [rbp+0x5ec],ebx
        ///000000000026 &lt;exit&gt;:
        ///58                      pop    rax
        ///e9 00 00 00 00          jm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfinitePoise {
            get {
                return ResourceManager.GetString("InfinitePoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,0,0,0,0,0,0,0,0,0,0
        ///10,1,0,0,0,0,0,0,1,1,1
        ///100000,1,1,1,1,1,1,1,1,1,1
        ///100100,1,1,1,1,1,1,0,1,1,1
        ///100200,1,1,1,1,1,1,1,1,1,1
        ///100300,1,1,1,1,1,1,1,1,1,1
        ///100400,1,1,1,1,1,1,1,1,1,1
        ///100500,1,1,1,1,1,1,1,1,1,1
        ///100600,1,1,1,1,1,1,1,1,1,1
        ///100700,1,1,1,1,1,1,1,1,1,1
        ///100800,1,1,1,1,1,1,1,1,1,1
        ///100900,1,1,1,1,1,1,1,1,1,1
        ///101000,1,1,1,1,1,1,1,1,1,1
        ///101100,1,1,1,1,1,1,1,1,1,1
        ///101200,1,1,1,1,1,1,1,1,1,1
        ///101300,1,1,1,1,1,1,1,1,1,1
        ///101400,1,1,1,1,1,1,1,1,1,1
        ///101500,1,1,1,1,1,1,0,1,1,1
        ///101600,1,1,1,1,1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Infusions {
            get {
                return ResourceManager.GetString("Infusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # 7 &lt;_main+0x7&gt;
        ///0f 85 e8 00 00 00       jne    f5 &lt;nothing_to_process&gt;
        ///c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 14 &lt;_main+0x14&gt;
        ///80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # 1b &lt;_main+0x1b&gt;
        ///75 5c                   jne    79 &lt;skip_adjust&gt;
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 8d 15 00 00 00 00    lea    rdx,[rip+0x0]        # 2e &lt;_main+0x2e&gt;
        ///4c 8d 05 00 00 00 00    lea    r8,[rip+0x0]      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemSpawn {
            get {
                return ResourceManager.GetString("ItemSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81 79 4c 80 7f 0a 00    cmp    DWORD PTR [rcx+0x4c],0xa7f80
        ///75 0e                   jne    17 &lt;normal&gt;
        ///48 85 c0                test   rax,rax
        ///75 09                   jne    17 &lt;normal&gt;
        ///41 83 f8 0f             cmp    r8d,0xf
        ///75 03                   jne    17 &lt;normal&gt;
        ///45 31 c0                xor    r8d,r8d
        ///000000000017 &lt;normal&gt;:
        ///44 88 84 08 a1 03 00    mov    BYTE PTR [rax+rcx*1+0x3a1],r8b
        ///00
        ///e9 00 00 00 00          jmp    24 &lt;normal+0xd&gt;.
        /// </summary>
        internal static string IvoryKnights {
            get {
                return ResourceManager.GetString("IvoryKnights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81 fa 78 46 02 20       cmp    edx,0x20024678
        ///75 12                   jne    1a &lt;check_next&gt;
        ///41 83 f8 01             cmp    r8d,0x1
        ///0f 85 bf 00 00 00       jne    d1 &lt;exit&gt;
        ///45 31 c0                xor    r8d,r8d
        ///e9 b7 00 00 00          jmp    d1 &lt;exit&gt;
        ///00000000001a &lt;check_next&gt;:
        ///81 fa 80 46 02 20       cmp    edx,0x20024680
        ///0f 85 ab 00 00 00       jne    d1 &lt;exit&gt;
        ///41 83 f8 01             cmp    r8d,0x1
        ///0f 85 a1 00 00 00       jne    d1 &lt;exit&gt;
        ///51                      push   rcx
        ///52                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IvorySkip {
            get {
                return ResourceManager.GetString("IvorySkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60355000,Aged Feather,1,0,0
        ///51030000,Aldia Key,1,0,0
        ///50840000,Antiquated Key,1,0,0
        ///50910000,Ashen Mist Heart,1,0,0
        ///62150000,Awestone,99,0,0
        ///50800000,Bastille Key,1,0,0
        ///6100000,Binoculars,1,0,0
        ///62160000,Black Separation Crystal,1,0,0
        ///62020000,Bone of Order,1,0,0
        ///50830000,Brightstone Key,1,0,0
        ///50940000,Champion&apos;s Tablet,1,0,0
        ///62050000,Cracked Blue Eye Orb,99,0,0
        ///62060000,Cracked Red Eye Orb,99,0,0
        ///51000000,Crushed Eye Orb,1,0,0
        ///62070000,Dragon Eye,1,0,0
        ///60405000,Dragon Head Stone,1,0,0
        ///6040501 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeyItems {
            get {
                return ResourceManager.GetString("KeyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53                      push   rbx
        ///48 bb 00 00 00 00 00    movabs rbx,0x0
        ///00 00 00
        ///48 39 c3                cmp    rbx,rax
        ///75 06                   jne    16 &lt;do_normal&gt;
        ///5b                      pop    rbx
        ///48 83 c4 68             add    rsp,0x68
        ///c3                      ret
        ///000000000016 &lt;do_normal&gt;:
        ///48 b8 00 00 00 00 00    movabs rax,0x8000000000000
        ///00 08 00
        ///5b                      pop    rbx
        ///e9 00 00 00 00          jmp    26 &lt;do_normal+0x10&gt;.
        /// </summary>
        internal static string Killbox {
            get {
                return ResourceManager.GetString("Killbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8b 0d 00 00 00 00       mov    ecx,DWORD PTR [rip+0x0]        # 6 &lt;_main+0x6&gt;
        ///ff c1                   inc    ecx
        ///ba 00 00 00 00          mov    edx,0x0
        ///80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # 14 &lt;_main+0x14&gt;
        ///74 25                   je     3b &lt;skip_lookup&gt;
        ///000000000016 &lt;loop_start&gt;:
        ///51                      push   rcx
        ///52                      push   rdx
        ///49 bf 00 00 00 00 00    movabs r15,0x0
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///41 ff d7                call   r15
        ///4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LevelUp {
            get {
                return ResourceManager.GetString("LevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # 7 &lt;_main+0x7&gt;
        ///e9 00 00 00 00          jmp    c &lt;_main+0xc&gt;.
        /// </summary>
        internal static string NoClip_CtrlCheck {
            get {
                return ResourceManager.GetString("NoClip_CtrlCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 39 f8                cmp    rax,rdi
        ///75 03                   jne    13 &lt;exit&gt;
        ///0f 57 c9                xorps  xmm1,xmm1
        ///000000000013 &lt;exit&gt;:
        ///58                      pop    rax
        ///f3 0f 11 4f 10          movss  DWORD PTR [rdi+0x10],xmm1
        ///e9 00 00 00 00          jmp    1e &lt;exit+0xb&gt;.
        /// </summary>
        internal static string NoClip_InAirTimer {
            get {
                return ResourceManager.GetString("NoClip_InAirTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8d 9e d8 00 00 00    lea    rbx,[rsi+0xd8]
        ///50                      push   rax
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 8b 00                mov    rax,QWORD PTR [rax]
        ///48 8b 80 d0 00 00 00    mov    rax,QWORD PTR [rax+0xd0]
        ///48 3b 41 08             cmp    rax,QWORD PTR [rcx+0x8]
        ///0f 85 6c 02 00 00       jne    292 &lt;exit&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 2c &lt;_main+0x2c&gt;
        ///83 3d 00 00 00 00 78    cmp    DWORD PTR [rip+0x0],0x78        # 33 &lt;_main+0x33&gt;
        ///0f 8e 59 02  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_RayCast {
            get {
                return ResourceManager.GetString("NoClip_RayCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4c 8b 7c 24 70          mov    r15,QWORD PTR [rsp+0x70]
        ///48 8b 43 08             mov    rax,QWORD PTR [rbx+0x8]
        ///52                      push   rdx
        ///48 89 c2                mov    rdx,rax
        ///48 81 e2 00 20 00 00    and    rdx,0x2000
        ///74 0d                   je     23 &lt;check_rt&gt;
        ///48 2d 00 20 00 00       sub    rax,0x2000
        ///c6 05 00 00 00 00 02    mov    BYTE PTR [rip+0x0],0x2        # 23 &lt;check_rt&gt;
        ///000000000023 &lt;check_rt&gt;:
        ///48 89 c2                mov    rdx,rax
        ///48 81 e2 00 02 00 00    and    rdx,0x200
        ///74 0d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_TriggersAndSpace {
            get {
                return ResourceManager.GetString("NoClip_TriggersAndSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52                      push   rdx
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 8b 12                mov    rdx,QWORD PTR [rdx]
        ///48 8b 92 d0 00 00 00    mov    rdx,QWORD PTR [rdx+0xd0]
        ///48 39 c2                cmp    rdx,rax
        ///0f 85 66 01 00 00       jne    184 &lt;original&gt;
        ///66 0f 6f b8 90 00 00    movdqa xmm7,XMMWORD PTR [rax+0x90]
        ///00
        ///53                      push   rbx
        ///41 50                   push   r8
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 8b 12                mov    rdx,QWORD PTR  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_UpdateCoords {
            get {
                return ResourceManager.GetString("NoClip_UpdateCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerald Herald,104020,103520,0
        ///Gilligan,104050,103550,102165
        ///Saulden,104140,103640,0
        ///Melentia,104210,103710,100971|102521
        ///Maughlin,104250,103750,0
        ///Chloanne,104260,103760,102625
        ///Rosabeth,104270,103770,102650
        ///Lenigrast,104280,103780,0
        ///Carhillion,104300,103800,102722
        ///Licia,104320,103820,102765
        ///Shalquoir,104370,103870,0
        ///
        ///
        ///.
        /// </summary>
        internal static string NPC {
            get {
                return ResourceManager.GetString("NPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8b 05 00 00 00 00       mov    eax,DWORD PTR [rip+0x0]        # 6 &lt;_main+0x6&gt;
        ///e9 00 00 00 00          jmp    b &lt;_main+0xb&gt;.
        /// </summary>
        internal static string OverrideGeneratorStartPositionRandom {
            get {
                return ResourceManager.GetString("OverrideGeneratorStartPositionRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51                      push   rcx
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 8b 09                mov    rcx,QWORD PTR [rcx]
        ///48 8b 89 d0 00 00 00    mov    rcx,QWORD PTR [rcx+0xd0]
        ///48 39 d9                cmp    rcx,rbx
        ///75 06                   jne    20 &lt;exit&gt;
        ///8b 81 68 01 00 00       mov    eax,DWORD PTR [rcx+0x168]
        ///000000000020 &lt;exit&gt;:
        ///59                      pop    rcx
        ///89 83 68 01 00 00       mov    DWORD PTR [rbx+0x168],eax
        ///e9 00 00 00 00          jmp    2c &lt;exit+0xc&gt;.
        /// </summary>
        internal static string PlayerNoDamage {
            get {
                return ResourceManager.GetString("PlayerNoDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 83 89 50 03 00 00 01    or     DWORD PTR [rcx+0x350],0x1
        ///50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # f &lt;_main+0xf&gt;
        ///48 85 c0                test   rax,rax
        ///74 31                   je     45 &lt;normal&gt;
        ///48 8b 80 e8 00 00 00    mov    rax,QWORD PTR [rax+0xe8]
        ///48 8b 40 18             mov    rax,QWORD PTR [rax+0x18]
        ///48 8b 40 20             mov    rax,QWORD PTR [rax+0x20]
        ///48 39 c8                cmp    rax,rcx
        ///75 1d                   jne    45 &lt;normal&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RepeatAct {
            get {
                return ResourceManager.GetString("RepeatAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///41 b8 01 00 00 00       mov    r8d,0x1
        ///b8 00 00 c8 42          mov    eax,0x42c80000
        ///66 0f 6e c8             movd   xmm1,eax
        ///48 81 ec 38 01 00 00    sub    rsp,0x138
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 81 c4 38 01 00 00    add    rsp,0x138
        ///c3                      ret.
        /// </summary>
        internal static string RestoreSpellcasts {
            get {
                return ResourceManager.GetString("RestoreSpellcasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40010000,Life Ring,1,0,0
        ///40010001,Life Ring+1,1,0,0
        ///40010002,Life Ring+2,1,0,0
        ///40010003,Life Ring+3,1,0,0
        ///40020000,Chloranthy Ring,1,0,0
        ///40020001,Chloranthy Ring+1,1,0,0
        ///40020002,Chloranthy Ring+2,1,0,0
        ///40030000,Royal Soldier&apos;s Ring,1,0,0
        ///40030001,Royal Soldier&apos;s Ring+1,1,0,0
        ///40030002,Royal Soldier&apos;s Ring+2,1,0,0
        ///40040000,First Dragon Ring,1,0,0
        ///40040001,Second Dragon Ring,1,0,0
        ///40040002,Third Dragon Ring,1,0,0
        ///40050000,Ring of Steel Protection,1,0,0
        ///40050001,Ring of Steel Protection+1,1,0,0
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rings {
            get {
                return ResourceManager.GetString("Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 3d 00 00 00 00    mov    QWORD PTR [rip+0x0],rdi        # 7 &lt;_main+0x7&gt;
        ///48 89 bb c0 00 00 00    mov    QWORD PTR [rbx+0xc0],rdi
        ///e9 00 00 00 00          jmp    13 &lt;_main+0x13&gt;.
        /// </summary>
        internal static string SaveTargetPtr {
            get {
                return ResourceManager.GetString("SaveTargetPtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49 8b 8f b0 00 00 00    mov    rcx,QWORD PTR [r15+0xb0]
        ///53                      push   rbx
        ///8b 1d 00 00 00 00       mov    ebx,DWORD PTR [rip+0x0]        # e &lt;_main+0xe&gt;
        ///41 3b 5f 68             cmp    ebx,DWORD PTR [r15+0x68]
        ///75 06                   jne    1a &lt;skip&gt;
        ///8b 35 00 00 00 00       mov    esi,DWORD PTR [rip+0x0]        # 1a &lt;skip&gt;
        ///00000000001a &lt;skip&gt;:
        ///5b                      pop    rbx
        ///e9 00 00 00 00          jmp    20 &lt;skip+0x6&gt;.
        /// </summary>
        internal static string SetAreaVariable {
            get {
                return ResourceManager.GetString("SetAreaVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///41 b8 00 00 00 00       mov    r8d,0x0
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret
        ///.
        /// </summary>
        internal static string SetEventOff {
            get {
                return ResourceManager.GetString("SetEventOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///41 b8 01 00 00 00       mov    r8d,0x1
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string SetEventOn {
            get {
                return ResourceManager.GetString("SetEventOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8d 15 00 00 00 00    lea    rdx,[rip+0x0]        # 7 &lt;_main+0x7&gt;
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 83 ec 48             sub    rsp,0x48
        ///e8 00 00 00 00          call   1a &lt;_main+0x1a&gt;
        ///48 83 c4 48             add    rsp,0x48
        ///c3                      ret.
        /// </summary>
        internal static string SetSpEffect {
            get {
                return ResourceManager.GetString("SetSpEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31010000,Soul Arrow,1,0,0
        ///31020000,Great Soul Arrow,1,0,0
        ///31030000,Heavy Soul Arrow,1,0,0
        ///31040000,Great Heavy Soul Arrow,1,0,0
        ///31050000,Homing Soul Arrow,1,0,0
        ///31060000,Heavy Homing Soul Arrow,1,0,0
        ///31070000,Homing Soulmass,1,0,0
        ///31080000,Homing Crystal Soulmass,1,0,0
        ///31090000,Soul Spear,1,0,0
        ///31100000,Crystal Soul Spear,1,0,0
        ///31110000,Shockwave,1,0,0
        ///31120000,Soul Spear Barrage,1,0,0
        ///31130000,Soul Shower,1,0,0
        ///31140000,Soul Greatsword,1,0,0
        ///31150000,Soul Vortex,1,0,0
        ///31160000,Soul Bolt,1,0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spells {
            get {
                return ResourceManager.GetString("Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49 bc 00 00 00 00 00    movabs r12,0x0
        ///00 00 00
        ///49 be 00 00 00 00 00    movabs r14,0x0
        ///00 00 00
        ///45 8b 6c 24 28          mov    r13d,DWORD PTR [r12+0x28]
        ///45 85 ed                test   r13d,r13d
        ///74 2c                   je     4a &lt;done&gt;
        ///49 8b 5c 24 20          mov    rbx,QWORD PTR [r12+0x20]
        ///31 f6                   xor    esi,esi
        ///48 83 ec 28             sub    rsp,0x28
        ///000000000029 &lt;loop_start&gt;:
        ///48 89 f0                mov    rax,rsi
        ///48 6b c0 18             imul   rax,rax,0x18
        ///48 01 d8            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnlockAllBonfires {
            get {
                return ResourceManager.GetString("UnlockAllBonfires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60970000,Titanite Shard,99,0,0
        ///60975000,Large Titanite Shard,99,0,0
        ///60980000,Titanite Chunk,99,0,0
        ///60990000,Titanite Slab,99,0,0
        ///61000000,Twinkling Titanite,99,0,0
        ///61030000,Petrified Dragon Bone,99,0,0
        ///61060000,Faintstone,99,0,0
        ///61070000,Boltstone,99,0,0
        ///61080000,Firedrake Stone,99,0,0
        ///61090000,Darknight Stone,99,0,0
        ///61100000,Poison Stone,99,0,0
        ///61110000,Bleed Stone,99,0,0
        ///61130000,Raw Stone,99,0,0
        ///61140000,Magic Stone,99,0,0
        ///61150000,Old Mundane Stone,99,0,0
        ///61160000,Palestone,99,0,0
        ///.
        /// </summary>
        internal static string UpgradeMaterials {
            get {
                return ResourceManager.GetString("UpgradeMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0f 5c c2                subps  xmm0,xmm2
        ///0f 29 47 50             movaps XMMWORD PTR [rdi+0x50],xmm0
        ///50                      push   rax
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 8b 00                mov    rax,QWORD PTR [rax]
        ///48 8b 40 58             mov    rax,QWORD PTR [rax+0x58]
        ///48 8b 80 f8 01 00 00    mov    rax,QWORD PTR [rax+0x1f8]
        ///48 8b 40 18             mov    rax,QWORD PTR [rax+0x18]
        ///48 8b 40 08             mov    rax,QWORD PTR [rax+0x8]
        ///48 05 50 01 00 00       add    rax,0x150
        ///48 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WarpCoordWrite {
            get {
                return ResourceManager.GetString("WarpCoordWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10655,Boss,Last Giant,92.18|-40.43|-147.47|0.00|92.18|-40.43|-147.47|55.84|92.18|-40.43|-147.47|0.00|0.00|0.00|0.00|1.00,0
        ///10655,Boss,Pursuer,139.12|10.05|-217.90|0.00|139.12|10.05|-217.90|58.79|139.12|10.05|-217.90|0.00|0.00|0.00|0.00|1.00,0
        ///31650,Boss,Dragonrider,-6.91|-14.66|283.71|0.00|-6.91|-14.66|283.71|36.76|-6.91|-14.66|283.71|0.00|0.00|0.00|0.00|1.00,0
        ///31660,Boss,Ornstein,-144.09|8.03|170.72|0.00|-144.09|8.03|170.72|45.42|-144.09|8.03|170.72|0.00|0.00|0.00|0.00|1.00,0
        ///18650,Boss,Flexile,2.91|-6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WarpLocations {
            get {
                return ResourceManager.GetString("WarpLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5225000,Aged Smelter Sword,1,5,0
        ///2540000,Aldia Hammer,1,10,101500
        ///4400000,Alonne Greatbow,1,10,102200
        ///5010000,Arced Sword,1,5,111400
        ///4060000,Archdrake Chime,1,10,102500
        ///2720000,Archdrake Mace,1,10,101600
        ///11250000,Archdrake Shield,1,10,102800
        ///3860000,Archdrake Staff,1,10,102400
        ///1380000,Ashen Warrior Sword,1,10,101000
        ///4660000,Avelyn,1,10,102300
        ///3930000,Azal&apos;s Staff,1,5,0
        ///2020000,Bandit Axe,1,10,101700
        ///2220000,Bandit Greataxe,1,10,101800
        ///1010000,Bandit&apos;s Knife,1,10,100400
        ///2560000,Barbed Club,1,5, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Weapons {
            get {
                return ResourceManager.GetString("Weapons", resourceCulture);
            }
        }
    }
}
